last_accessed: 2018-05-01 00:00:00
# YYYY-MM-DD HH:MM:SS +HHMM

from:
password:

to: 

gmail:
    smtp_server: smtp.gmail.com
    smtp_port: 465

feeds:
    - https://google.com
    - http://www.lightspeedmagazine.com/rss-2/
    - https://uncannymagazine.com/feed/
